### PR TITLE
keepItemsInArray has been moved to ArrayUtility

### PR DESCRIPTION
**Pull request by cvisys**

### CODE REVIEW

**Comment by fsaris** [comment]
Tnx for the pull request. Since what TYPO3 is this available in arrayUtility?

**Comment by cvisys** [comment]
Since 7.6. Wasn't in 6.2

**Comment by frans-beech-it** [comment]
Ok then the minimum needs to be raised first to 7.6

**Comment by cvisys** [comment]
That would be nice. Would also allow cleaner code instead of all the compat_version checks.

**Comment by kasperligaard** [comment]
@frans-beech-it Are you comtemplating a new release within the coming weeks, which incorporates this bugfix?

**Comment by frans-beech-it** [comment]
First need to release a new version that's still compatible with TYPO3 6.2. Will try to have a look next week

**Comment by kasperligaard** [comment]
@frans-beech-it : How's it looking? Did you get around to look in to this?

**Comment by frans-beech-it** [comment]
this PR is obsolete correct?

**Comment by cvisys** [comment]
Correct.

**Pull request closed without merging**
