### PR TITLE
[FEATURE] Allow to use typolink for the redirects URL

### LINKED ISSUE #124: Allow to use typolink for the redirects URL
Hi,

It would be great if we could use link like `t3://page?uid=1` for the redirects URL (login_redirect_url and no_access_redirect_url).

Thanks

### PR DESCRIPTION
**Pull request by echavaillaz**
Pull request to resolve #124

Thanks

### CODE REVIEW

**Comment by frans-beech-it** [comment]
@echavaillaz is this supported since 9LTS or also in 8LTS?

**Comment by echavaillaz** [comment]
I just test with TYPO3 9. Do you want that I also try on TYPO3 8?

**Comment by echavaillaz** [comment]
It works only with TYPO3 9, I will adapt my PR.

**Comment by echavaillaz** [comment]
Ok, now it's compatible also with TYPO3 8.

**Comment by frans-beech-it** [comment]
tnx for the PR

**Pull request merged**
