### PR TITLE
[TASK] Add a new signalSlot to override the redirectUrls

### PR DESCRIPTION
**Pull request by dhuf**

### CODE REVIEW

**Comment by frans-beech-it** [comment]
Hi Daniel,

Tnx for your this feature. Could you maybe add a few lines about this to the documentation? Than it's ready to be merged :smiley: 

Frans

**Comment by dhuf** [comment]
@frans-beech-it hope it is ok like this. 
Thanks a lot.
Daniel

**Comment by dhuf** [comment]
@frans-beech-it any news on it ? Thanks

**Comment by frans-beech-it** [comment]
@dhuf tnx for the contribution. And sorry for the delay

**Pull request merged**
