### PR TITLE
Task/add typo3 10 4 support

### PR DESCRIPTION
**Pull request by andreas-tritum**
Adds support for TYPO3 10.4

### CODE REVIEW

**Comment by dev-rke** [comment]
Hi,

i tested your branch on two different environments (naked TYPO3 10 and a nearly production ready TYPO3 10) and can confirm it works as perfectly as the previous version. :-) 
My tests contained downloading protected files and showing protected images with a logged in frontend user. 
Furthermore i tested if access to these files is restricted when not logged in.
As i do not use the tree feature i did not test this specific functionality.

Thanks for sharing!

**Comment by dev-rke** [comment]
Small issue when previewing files from backend filelist module and in image references. Preview images are not loaded and throw the following error:
```
Too few arguments to function BeechIt\FalSecuredownload\Controller\BePublicUrlController::dumpFile(), 1 passed and exactly 2 expected 
```

I assume the implementation of the other v10 branch would be helpful, as it works there.

**Comment by andreas-tritum** [comment]
Thank you for the hint :-)
I cherry-picked according commit of @joey-beech-it BE-Viewing now works in my installation

**Comment by joey-beech-it** [comment]
@andreas-tritum @dev-rke 

After an internal discussion yesterday which solution for the middleware would be the best. We chose the one @andreas-tritum made.

Today I will try to make a final pull request based on @andreas-tritum pull-request with some other code changes we think is needed. I will both notify you when this is ready for testing.

@andreas-tritum Would you like to be mentioned in the readme as a thanks for helping us update to 10.4?

**Comment by andreas-tritum** [comment]
> @andreas-tritum Would you like to be mentioned in the readme as a thanks for helping us update to 10.4?

Thank you for asking. I would appreciate, if my company [TRITUM GmbH](https://www.tritum.de/) would be mentioned instead of me.

**Comment by joey-beech-it** [comment]
With combining of https://github.com/beechit/fal_securedownload/pull/147 and this pull request https://github.com/beechit/fal_securedownload/pull/148, a new pull request has been made for the final variant of the update
https://github.com/beechit/fal_securedownload/pull/149

**Pull request merged**
