### PR TITLE
[MERGE] Update for v10

### PR DESCRIPTION
**Pull request by joey-beech-it**

### CODE REVIEW

**Comment by dev-rke** [comment]
Hi,
installing via composer triggers a install warning in extension manager due to version requirements in ext_emconf.php:
`'typo3' => '10.4.20 - 10.4.99',`
I use TYPO3 10.4.6, i assume the minimum version requirement should be 10.4.0 or 9.5.20.

**Comment by dev-rke** [comment]
The updated version works as expected when i am already logged in.

When i am not logged in (using private mode of the browser) and try to access an access protected file direct via url, the following error raises:

```
Call to a member function fetchGroupData() on null
in /var/www/web/typo3conf/ext/fal_securedownload/Classes/Hooks/FileDumpHook.php line 326

    protected function initializeUserAuthentication()
    {
        if ($this->feUser === null) {
            $this->feUser = $GLOBALS['TSFE']->fe_user;
            $this->feUser->fetchGroupData();
        }
    }

    /**
```

**Comment by joey-beech-it** [comment]
> Hi,
> installing via composer triggers a install warning in extension manager due to version requirements in ext_emconf.php:
> `'typo3' => '10.4.20 - 10.4.99',`
> I use TYPO3 10.4.6, i assume the minimum version requirement should be 10.4.0 or 9.5.20.

This should be fixed now, using minimum of 10.4.6 since this was a security release

**Comment by joey-beech-it** [comment]
@dev-rke 

> The updated version works as expected when i am already logged in.
> 
> When i am not logged in (using private mode of the browser) and try to access an access protected file direct via url, the following error raises:
> 
> ```
> Call to a member function fetchGroupData() on null
> in /var/www/web/typo3conf/ext/fal_securedownload/Classes/Hooks/FileDumpHook.php line 326
> 
>     protected function initializeUserAuthentication()
>     {
>         if ($this->feUser === null) {
>             $this->feUser = $GLOBALS['TSFE']->fe_user;
>             $this->feUser->fetchGroupData();
>         }
>     }
> 
>     /**
> ```

Will look into this asap

**Comment by joey-beech-it** [comment]
@dev-rke 

we added an extra check to see if FrontendUserAuthentication is implemented. we were not able to reproduce the error with the steps that you told us.

If the error happens again, could you tell us the following.

- Logged in to BE (yes/no), if so Admin (Yes/No).
- Logged in to FE (yes/no).
- Logged in with feUser should be allowed to download the file (Yes/No).
- Example of the download URL you were trying to reach.
- Full stacktrace of the error.


```
    /**
     * Initialise feUser
     */
    protected function initializeUserAuthentication()
    {
        if ($this->feUser === null) {
            $this->feUser = $GLOBALS['TSFE']->fe_user;
            if ($this->feUser instanceof FrontendUserAuthentication) {
                $this->feUser->fetchGroupData();
            }

        }
    }
```

**Comment by dev-rke** [comment]
Hi @joey-beech-it ,

thanks, i will give it a try. :-)

**Comment by dev-rke** [comment]
Hi @joey-beech-it ,

i tested it again, my assumption is the previous version was working better.
The current version does not detect anymore that i am already logged in using my FrontendUser.

I am logged in to backend under a different domain with an backend admin user, we use seperate subdomains to access frontend and backend. The frontend should be not able to detect that i am logged in, the behaviour does also not change, when i log out of the backend (but still logged in with my FrontendUser).

The FrontendUser should be able to download the file, this is not working anymore, but was before.
When i try to access the file, i get the following output: 
"Authentication required!"

When i try to access the protected file with the private mode of the browser (no cookie and no authentication is set), i get the same output: 
"Authentication required!"

The bug i reported is fixed, but unfortunately there is now a new one.

My local development url to the access protected file:
https://myproject.dev.env/index.php?eID=dumpFile&t=f&f=18048&token=680aaa6e4606e4c6f6f55028b9153479f740e33c

Thanks for your support! :+1:

**Comment by joey-beech-it** [comment]
@dev-rke 

Could you verify you are using this pull request?

Since the update no URL should use the `eID=dumpFile` tag anymore, this is due through late initiating of FrontendUserAuthentication after `eIdHandler` in the middleware stack.

All dump url's should be generated with `secureDownload=dumpFile`

https://myproject.dev.env/index.php?secureDownload=dumpFile&t=f&f=72&token=69da3b3e30ee39afcbe74ed9fd4347c3fd2713d7&download=

Could you verify your middlewarestack looks something like the following?
image

Do you have any custom configuration that could affect his?

**Comment by dev-rke** [comment]
Hi @joey-beech-it ,

i will verify, if there is any custom config.
Currently it seems to look as expected, here a screenshot  from my instance:
grafik

**Comment by dev-rke** [comment]
Verified my config.
Git branch is checked out at 89a0ddb6ab2881e5891d3452050b0bda68ca2276.
I use RouteEnhancers for news and blog extension, i disabled them now.
I also have enabled Feature Toggle "Rearranged redirect middlewares", which i turned off for now for testing.
My LocalConfiguration-Settings:
```php
'fal_securedownload' => [
            'force_download' => '0',
            'force_download_for_ext' => '',
            'login_redirect_url' => '',
            'no_access_redirect_url' => '',
            'resumable_download' => '1',
            'track_downloads' => '0',
],
```

My user is in a group "typo3local", which is also set as restriction for my custom file storage "typo3local".
For testing i also included the FileTree TypoScript, which typically is not needed for my purposes.
I also tried to move fal_securedownload entry in PackageStates.php to the beginning.

Unfortunately it still does not work. :-/

My next approach will be to Dissect the last commits.
Did anything change regarding the installation process since the last stable version?
I ensured all steps described here have been done:
https://docs.typo3.org/p/beechit/fal-securedownload/2.2/en-us/Installation/Index.html

**Comment by fsaris** [comment]
@dev-rkv how do you generate the urls? Do you use the file tree plugin for the extension?
As joey mentioned the urls should have a different key. This is something that the publicUrl hook should take care of

**Comment by dev-rke** [comment]
Hi @fsaris ,
i place files using RTE file links and via the file links content element.
File tree is not used in my instance.
I understand that urls should not use eID but secureDownload as key, but unfortunately it does not work.

In which class does the core generate these dumpFile URLs by default? Where do you hook into this process?
Could you give me a short overview about the process, so i am able to debug it? :-)

**Comment by dev-rke** [comment]
Ok, minor update: when i access my protected file storage from backend and preview the file using the preview button, i am able to get the protected file - furthermore i can see it is using the secureDownload=dumpFile url parameter:
/typo3/index.php?route=%2Fajax%2Ffal_securedownloads%2Fdump_file&token=937ebc5ddc8943d4e2dd325260f15b414ea4b13d&secureDownload=dumpFile&t=f&f=26169&fal_token=d57594359c0fd8dc06d53fda68eebc04fe8b8403

**Comment by dev-rke** [comment]
Ok, some progress at the front:
When i change ext_localconf.php to this
```php
// FileDumpEID hook
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['FileDumpEID.php']['checkFileAccess']['FalSecuredownload'] =
    \BeechIt\FalSecuredownload\Hooks\FileDumpHook::class;


    /** @var \TYPO3\CMS\Extbase\SignalSlot\Dispatcher $signalSlotDispatcher */
    $signalSlotDispatcher = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\SignalSlot\Dispatcher::class);

    // Public url rendering in BE context
    if (!(TYPO3_REQUESTTYPE & TYPO3_REQUESTTYPE_CLI)) {
        $signalSlotDispatcher->connect(
            \TYPO3\CMS\Core\Resource\ResourceStorage::class,
            \TYPO3\CMS\Core\Resource\ResourceStorage::SIGNAL_PreGeneratePublicUrl,
            \BeechIt\FalSecuredownload\Aspects\PublicUrlAspect::class,
            'generatePublicUrl'
        );
    }
if (TYPO3_MODE === 'BE') {
    // Page module hook
```

then the url in the frontend gets modified:
https://myproject.dev.env/index.php?route=%2Fajax%2Ffal_securedownloads%2Fdump_file&token=63e3b5a0c115726054d16d30540c29d1fdf76d0d&secureDownload=dumpFile&t=f&f=23198&fal_token=d50bba87325bf3fef5b94c7d1cc857eb9926d109

My change is to move the TYPO3_MODE-Condition downwards to ensure PublicUrlAspect is available in Frontend, too.

Are you sure the hook / signal registration for url generation is correct?
I don't see any implementation which else could define secureDownload links except the PublicUrlAspect, which is available for backend only. 
Could you please check (no offense) if there are any uncommitted files left in your working directory? 
Thats a typical \*\*\*censored\*\*\* i do in my projects. :D

Thanks for the support. :-)

**Comment by dev-rke** [comment]
I verified the behaviour using a fresh and clean TYPO3 v10 installation using PHP 7.4.
Unfortunately links still use eid=dumpFile.

**Comment by frans-beech-it** [comment]
Hi @dev-rke,

did you also try the filetree plugin or only links in the RTE.

Frans

**Comment by dev-rke** [comment]
I tried links in RTE and via fluid_styled_content filelist content element.
The filetree was not used before in the project, so i did not test it, as i do not need it.

**Comment by joey-beech-it** [comment]
@dev-rke 

With combining of #148 and this pull request #147, a new pull request has been made for the final variant of the update
#149

Due to this, we close this pull request.

**Comment by dev-rke** [comment]
Great, i will test it today. :-)

**Pull request closed without merging**
